version: "2"

linters:
  enable:
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - revive
    - forbidigo
    - tagliatelle
    - goconst
    - gocritic
    - gocyclo
    - govet
    - errcheck
    - gosec
    - nolintlint

formatters:
  enable:
    - gofumpt
    - goimports

linters-settings:
  forbidigo:
    forbid:
      - 'ioutil\.*'
  tagliatelle:
    case:
      use-field-name: false
      rules:
        yaml: goCamel
        json: snake
